spring:
  datasource:
    url: jdbc:mysql://localhost/eggplant
    username: root
    password: 1248
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate:
    SQL: debug
    type: trace